/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { Glean } from "@gleanwork/api-client";
import dotenv from "dotenv";
dotenv.config();

const client = new GleanClient({
  apiKey: process.env.GLEAN_API_KEY!,
  basePath: process.env.GLEAN_BASE_PATH || "https://api.glean.com",
});

export interface GleanDoc {
  title?: string;
  snippet?: string;
  url?: string;
}

export async function searchQuery(query: string, pageSize = 5): Promise<GleanDoc[]> {
  try {
    const res = await client.search.search({ query, pageSize });
    return res.results?.map(r => ({
      title: r.title,
      snippet: r.snippet,
      url: r.url,
    })) || [];
  } catch (e) {
    console.error("Glean search error:", e);
    return [];
  }
}