/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchQuery } from "./gleanClient";

const testQueries = [
  "2023 sales report",
  "R&D strategy pdf",
  "Org chart 2024",
  "testop_inactive",
  "testoldfile_inactive",
];

(async () => {
  for (const query of testQueries) {
    const results = await searchQuery(query);
    if (results.length === 0) {
      console.warn(`⚠️ No results for "${query}" — possible indexing gap.`);
    } else {
      console.log(`✅ Found ${results.length} results for "${query}"`);
    }
  }
})();
